Repository microsoft/LSKV, pull requests merged in 2022-10, with the labels that each got.

#107 Use time.Sleep not os.Sleep in etcd tests
  patches/0001-etcd-patches.patch
Labels: bug

#92 Member list
  proto/etcd.proto
  src/app/app.cpp
  src/app/node_data.h
Labels: enhancement

#71 Cluster Id
  src/app/app.cpp
Labels: enhancement

#104 CI benchmarking
  .github/workflows/benchmark.yml
  .github/workflows/check-issues.yaml
  .github/workflows/ci.yml
  analysis.ipynb
  benchmark/etcd.py
Labels: benchmark, automation

#124 Move VERBOSE_LOGGING def to cmake
  CMakeLists.txt
  README.md
  src/app/app.cpp
  src/app/index.cpp
  src/app/leases.cpp
Labels: enhancement

#125 Set repo on assignee gh command
  .github/workflows/pr-assignee.yml
Labels: automation

#126 Ignore pyc files
  .gitignore
Labels: enhancement

#128 Add CCF 3.0.0dev6 constitution files
  Dockerfile.sgx
  Dockerfile.virtual
  constitution/actions.js
  constitution/apply.js
  constitution/resolve.js
  constitution/validate.js
Labels: enhancement

#132 Consolidate workflows
  .github/workflows/check-issues.yaml
  .github/workflows/ci-checks.yml
  .github/workflows/ci.yml
Labels: automation

#133 Perf system
  Makefile
  benchmark/all.py
  benchmark/analysis.py
  benchmark/ci.py
  benchmark/common.py
  benchmark/perf-analysis.ipynb
  benchmark/perf_system.py
  benchmark/stores.py
  requirements.txt
  scripts/ci-checks.sh
Labels: benchmark

#144 Add labels to dockerfiles
  Dockerfile.sgx
  Dockerfile.virtual
Labels: automation
